name: CI - Prodution

on:
  workflow_dispatch:
    inputs:
      reason:
        type: string
        required: true

  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  build-image:
    name: "Docker Image Build"
    if: github.event.pull_request.merged == true || inputs.reason != ''
    uses: ./.github/workflows/build-image.yml
    with:
      CONTAINER_REGISTRY_URL: "${{vars.CONTAINER_REGISTRY_URL}}"
      PORT: "${{vars.PORT_PRD}}"
      DATABASE_NAME: "${{vars.DATABASE_NAME_PRD}}"
      MAIL_USER_NAME: "${{vars.MAIL_USER_NAME_PRD}}"
      MAIL_USER_EMAIL: "${{vars.MAIL_USER_EMAIL_PRD}}"
      AZURE_STORAGE_NAME: "${{vars.AZURE_STORAGE_NAME_PRD}}"
      AWS_BUCKET_NAME: "${{vars.AWS_BUCKET_NAME_PRD}}"
      WEBSITE_URL: "${{vars.WEBSITE_URL_PRD}}"
      ENVIRONMENT: "prd"
    secrets: 
      CONTAINER_REGISTRY_USER: "${{secrets.CONTAINER_REGISTRY_USER}}"
      CONTAINER_REGISTRY_PWD: "${{secrets.CONTAINER_REGISTRY_PWD}}"
      AZURE_STORAGE_ACCESS_KEY: "${{secrets.AZURE_STORAGE_ACCESS_KEY_PRD}}"
      DATABASE_URI: "${{secrets.DATABASE_URI_PRD}}"

  deploy:
    name: "Deploy on Production"
    uses: ./.github/workflows/deploy-image.yml
    needs: build-image
    with:
      CONTAINER_REGISTRY_URL: "${{vars.CONTAINER_REGISTRY_URL}}"
      SERVER_HOSTNAME: "${{vars.SERVER_HOSTNAME_PRD}}"
      ENVIRONMENT: "prd"
    secrets: 
      CONTAINER_REGISTRY_USER: "${{secrets.CONTAINER_REGISTRY_USER}}"
      CONTAINER_REGISTRY_PWD: "${{secrets.CONTAINER_REGISTRY_PWD}}"
